name: Pylint CI

on:
  push:

jobs:
  run-pylint-and-fail-under-nine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install pylint
        run: |
          pip install pylint

      - name: Lint with pylint
        run: |
          pylint --fail-under=9 **/*.py